# Generated by Django 3.0.1 on 2019-12-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('min_date', models.IntegerField(max_length=2)),
                ('max_date', models.IntegerField(max_length=2)),
                ('sum', models.IntegerField(max_length=5)),
                ('early_repayment', models.BooleanField(default=True, verbose_name='early repayment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ManyToManyField(to='webapp.Product')),
            ],
            options={
                'verbose_name': 'consumer',
                'verbose_name_plural': 'consumers',
            },
        ),
    ]
