# Generated by Django 3.0.1 on 2019-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_of_end',
        ),
        migrations.AlterField(
            model_name='product',
            name='max_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_date',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum',
            field=models.IntegerField(),
        ),
    ]
